server:
  port: 8091
  servlet:
    context-path: /kafka-api

transwarp:
  kerberos:
    # 集群开启kerberos认证
    security: true

spring:
  kafka:
    # kafka集群的连接地址
    bootstrap-servers: SASL_PLAINTEXT://p-tdhsit-mg1:9092,SASL_PLAINTEXT://p-tdhsit-mg2:9092,SASL_PLAINTEXT://p-tdhsit-mg3:9092
    producer:
      acks: all                                                                                               # 等待应答的副本：所有
      retries: 3                                                                                              # 发送失败重试次数
      batch-size: 1048576                                                                                     # 每次发送的大小：1M
      buffer-memory: 104857600                                                                                # 发送缓冲区大小：1M
      key-serializer: org.apache.kafka.common.serialization.StringSerializer                                  # key的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer                                # value的序列化方式
    consumer:
      group-id: gs-test1                                                                                      # 消费组id
      enable-auto-commit: true                                                                               # 是否自动确认offset
      auto-offset-reset: earliest                                                                             # 设置消费的模式，从头消费
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer                              # key的反序列化方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer                            # key的反序列化方式
    security:
      protocol: SASL_PLAINTEXT
    properties:
      sasl:
        kerberos:
          service:
            name: kafka
        mechanism: GSSAPI